[package]
name = "fairu-entity"
version = { workspace = true }
edition = "2021"
publish = false

[lib]
name = "fairu_entity"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
version = "1.1.0"
